name: phone_parser
description: Dart library for parsing phone numbers with auto synced with Google libphonenumber. Inspired by Google's libphonenumber and PhoneNumberKit for ios.
version: 0.0.2
homepage: https://github.com/sumitsharansatsangi/phone_parser

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.16.0
  xml: ^6.6.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
