import 'dart:io';

import 'package:phone_parser/src/download_file/download_file.dart';

Future<void> main() async {
  final outputFile = _resolveBundledMetadataFile();
  final outputDir = outputFile.parent;

  if (!await outputDir.exists()) {
    await outputDir.create(recursive: true);
  }

  final tempDir = await Directory.systemTemp.createTemp(
    'phone_parser_metadata_',
  );

  try {
    final downloadedPath = await downloadMetadata(tempDir.path);
    if (downloadedPath == null) {
      stderr.writeln(
        'Failed to download metadata. Bundled snapshot was not updated.',
      );
      exitCode = 1;
      return;
    }

    final jsonString = await File(downloadedPath).readAsString();
    await outputFile.writeAsString(_buildBundledMetadataDart(jsonString));
    stdout.writeln(
      'Bundled metadata Dart snapshot updated at ${outputFile.path}',
    );
  } finally {
    if (await tempDir.exists()) {
      await tempDir.delete(recursive: true);
    }
  }
}

File _resolveBundledMetadataFile() {
  final scriptDir = File.fromUri(Platform.script).parent;
  final repoRoot = scriptDir.parent;
  return File.fromUri(
    repoRoot.uri.resolve(
      'lib/src/metadata/bundled_metadata.g.dart',
    ),
  );
}

String _buildBundledMetadataDart(String jsonString) {
  return """
// Generated by tool/update_bundled_metadata.dart.
// Do not edit by hand.

const bundledMetadataJson = r'''$jsonString''';
""";
}
